CREATE TABLE goalkeeper_reportstest(
report_id VARCHAR(10) NOT NULL,
player VARCHAR(20) NOT NULL,
club_played INTEGER NOT NULL,
date_played DATE,
ht_score VARCHAR(10),
ft_score VARCHAR(10),
scouted_by VARCHAR(25) NOT NULL,
handling INTEGER,
shot_stopping INTEGER,
tendancy_to_punch INTEGER,
tendancy_to_catch INTEGER,
positioning INTEGER,
recovery_saves INTEGER,
control_when_recieving INTEGER,
right_foot INTEGER,
left_foot INTEGER,
dead_ball_kicks INTEGER,
kicking_out_of_hands INTEGER,
throwing INTEGER,
kicking_under_pressure INTEGER,
kicking_when_given_time INTEGER,
dealing_with_crosses INTEGER,
one_v_one INTEGER,
dealing_with_through_ball INTEGER,
agility INTEGER,
reactions INTEGER,
strength INTEGER,
speed INTEGER,
bravery INTEGER,
leadership INTEGER,
presence INTEGER,
communication INTEGER,
reaction_to_mistake INTEGER,
rating VARCHAR(2),
notes VARCHAR(1000)
);
